### ISSUE TITLE
license

### ISSUE THREAD

**Issue by pascalBokBok** [richardbrinkman/git-migration-hook#3]
Hi Richard,
Would you consider changing or dual license git-migration-hook to a less strict license such as MIT or BSD?
I think that if I distribute my code with a gpl licensed git-migration-hook my code will fall under the GPL also.

**Comment by richardbrinkman** [comment]
I really don't care what you do with these git hooks. Feel free to use them in any way you like.

**Comment by richardbrinkman** [comment]
It appears, according to http://choosealicense.com/licenses/, that having no license at all still forbids Distribution, Modification and Sublicensing. Therefore I have changed it to the MIT license, which seems to be the least restrictive.

**Comment by pascalBokBok** [comment]
Thanks :smile:
