### ISSUE TITLE
How to run all migrations after installation?

### ISSUE THREAD

**Issue by tueena-lib** [richardbrinkman/git-migration-hook#5]
Nice idea! Thank you.

Do you have a script or a suggestion to run all up scripts after the installation?

**Comment by richardbrinkman** [comment]
Something like the following?

```bash
cat migrations/*-up.sql | mysql -u your_username your_databasename
```

**Comment by tueena-lib** [comment]
Yes, this runs the scripts in the proper order. Thank you!
